### ISSUE TITLE
Is it possible to alter a graph after its creation?

### ISSUE THREAD

**Issue by troelsarvin** [s1ck/graph#110]
Is it possible to alter a graph after its creation, or is a graph read-only?
I.e. is something like this possible?
https://docs.rs/dendron/0.1.5/dendron/node/struct.Node.html#method.create_as_first_child

**Comment by waynevanson** [comment]
Read only from the looks of it.
I don't see any mutability in the API.
Implementations use `Box<T>` for values, meaning values cannot be added.

Petgraph is a library that uses mutability.

**Comment by s1ck** [comment]
We started out with immutable graphs and focused on creating such graphs in a parallel fashion. Updating our internal CSR data structure is certainly possible, but would require quite some changes. 

For small graphs, I can imagine a builder API that allows you to add nodes and edges and turns this into a mutable graph. Would that be something that works? Otherwise, as @waynevanson suggested, petgraph has mutable graphs, but no scale-up capabilities.
